export const reviews = [
  {
    id: 1,
    age: 34,
    location: 'New York, United States',
    number_book: 2019,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 2,
    age: 34,
    location: 'New York, United States',
    number_book: 2009,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 3,
    age: 34,
    location: 'New York, United States',
    number_book: 1139,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 4,
    age: 34,
    location: 'New York, United States',
    number_book: 1039,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 5,
    age: 34,
    location: 'New York, United States',
    number_book: 1009,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 6,
    age: 34,
    location: 'New York, United States',
    number_book: 999,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 7,
    age: 34,
    location: 'New York, United States',
    number_book: 339,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 8,
    age: 34,
    location: 'New York, United States',
    number_book: 239,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 9,
    age: 34,
    location: 'New York, United States',
    number_book: 139,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 10,
    age: 34,
    location: 'New York, United States',
    number_book: 129,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 11,
    age: 34,
    location: 'New York, United States',
    number_book: 129,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 12,
    age: 34,
    location: 'New York, United States',
    number_book: 129,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 13,
    age: 34,
    location: 'New York, United States',
    number_book: 129,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 14,
    age: 34,
    location: 'New York, United States',
    number_book: 129,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 15,
    age: 34,
    location: 'New York, United States',
    number_book: 129,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 16,
    age: 34,
    location: 'New York, United States',
    number_book: 129,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 17,
    age: 34,
    location: 'New York, United States',
    number_book: 129,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
  {
    id: 18,
    age: 34,
    location: 'New York, United States',
    number_book: 129,
    average_rating: 8,
    highest: 10,
    lowest: 0,
  },
]
